name: Court Booking Automation

on:
  schedule:
    # Run at 12:00:30 AM Newfoundland time (UTC-3:30)
    # In UTC: 3:30:30 AM
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  book-courts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest'

    - name: Install dependencies
      run: |
        sudo apt-get install -y libgbm-dev
        pip install -r requirements.txt

    - name: Generate config file
      env:
        # User 1
        USER1_LOGIN_URL: ${{ secrets.USER1_LOGIN_URL }}
        USER1_LOGIN_USERNAME: ${{ secrets.USER1_LOGIN_USERNAME }}
        USER1_LOGIN_PASSWORD: ${{ secrets.USER1_LOGIN_PASSWORD }}
        USER1_BOOKING_DATE: ${{ secrets.USER1_BOOKING_DATE }}
        USER1_BOOKING_TIME: ${{ secrets.USER1_BOOKING_TIME }}
        USER1_BOOKING_FACILITY: ${{ secrets.USER1_BOOKING_FACILITY }}
        USER1_BOOKING_CELL_NUMBER: ${{ secrets.USER1_BOOKING_CELL_NUMBER }}
        USER1_BOOKING_REASON: ${{ secrets.USER1_BOOKING_REASON }}

        # User 2
        USER2_LOGIN_URL: ${{ secrets.USER2_LOGIN_URL }}
        USER2_LOGIN_USERNAME: ${{ secrets.USER2_LOGIN_USERNAME }}
        USER2_LOGIN_PASSWORD: ${{ secrets.USER2_LOGIN_PASSWORD }}
        USER2_BOOKING_DATE: ${{ secrets.USER2_BOOKING_DATE }}
        USER2_BOOKING_TIME: ${{ secrets.USER2_BOOKING_TIME }}
        USER2_BOOKING_FACILITY: ${{ secrets.USER2_BOOKING_FACILITY }}
        USER2_BOOKING_CELL_NUMBER: ${{ secrets.USER2_BOOKING_CELL_NUMBER }}
        USER2_BOOKING_REASON: ${{ secrets.USER2_BOOKING_REASON }}

        # User 3
        USER3_LOGIN_URL: ${{ secrets.USER3_LOGIN_URL }}
        USER3_LOGIN_USERNAME: ${{ secrets.USER3_LOGIN_USERNAME }}
        USER3_LOGIN_PASSWORD: ${{ secrets.USER3_LOGIN_PASSWORD }}
        USER3_BOOKING_DATE: ${{ secrets.USER3_BOOKING_DATE }}
        USER3_BOOKING_TIME: ${{ secrets.USER3_BOOKING_TIME }}
        USER3_BOOKING_FACILITY: ${{ secrets.USER3_BOOKING_FACILITY }}
        USER3_BOOKING_CELL_NUMBER: ${{ secrets.USER3_BOOKING_CELL_NUMBER }}
        USER3_BOOKING_REASON: ${{ secrets.USER3_BOOKING_REASON }}

        # User 4
        USER4_LOGIN_URL: ${{ secrets.USER4_LOGIN_URL }}
        USER4_LOGIN_USERNAME: ${{ secrets.USER4_LOGIN_USERNAME }}
        USER4_LOGIN_PASSWORD: ${{ secrets.USER4_LOGIN_PASSWORD }}
        USER4_BOOKING_DATE: ${{ secrets.USER4_BOOKING_DATE }}
        USER4_BOOKING_TIME: ${{ secrets.USER4_BOOKING_TIME }}
        USER4_BOOKING_FACILITY: ${{ secrets.USER4_BOOKING_FACILITY }}
        USER4_BOOKING_CELL_NUMBER: ${{ secrets.USER4_BOOKING_CELL_NUMBER }}
        USER4_BOOKING_REASON: ${{ secrets.USER4_BOOKING_REASON }}
      run: |
        echo "[USER1_LOGIN]" > config.ini
        echo "url = ${USER1_LOGIN_URL}" >> config.ini
        echo "username = ${USER1_LOGIN_USERNAME}" >> config.ini
        echo "password = ${USER1_LOGIN_PASSWORD}" >> config.ini
        echo "" >> config.ini
        echo "[USER1_BOOKING]" >> config.ini
        echo "date = ${USER1_BOOKING_DATE}" >> config.ini
        echo "time = ${USER1_BOOKING_TIME}" >> config.ini
        echo "facility = ${USER1_BOOKING_FACILITY}" >> config.ini
        echo "cell_number = ${USER1_BOOKING_CELL_NUMBER}" >> config.ini
        echo "booking_reason = ${USER1_BOOKING_REASON}" >> config.ini
        echo "" >> config.ini
        
        echo "[USER2_LOGIN]" >> config.ini
        echo "url = ${USER2_LOGIN_URL}" >> config.ini
        echo "username = ${USER2_LOGIN_USERNAME}" >> config.ini
        echo "password = ${USER2_LOGIN_PASSWORD}" >> config.ini
        echo "" >> config.ini
        echo "[USER2_BOOKING]" >> config.ini
        echo "date = ${USER2_BOOKING_DATE}" >> config.ini
        echo "time = ${USER2_BOOKING_TIME}" >> config.ini
        echo "facility = ${USER2_BOOKING_FACILITY}" >> config.ini
        echo "cell_number = ${USER2_BOOKING_CELL_NUMBER}" >> config.ini
        echo "booking_reason = ${USER2_BOOKING_REASON}" >> config.ini
        echo "" >> config.ini
        
        echo "[USER3_LOGIN]" >> config.ini
        echo "url = ${USER3_LOGIN_URL}" >> config.ini
        echo "username = ${USER3_LOGIN_USERNAME}" >> config.ini
        echo "password = ${USER3_LOGIN_PASSWORD}" >> config.ini
        echo "" >> config.ini
        echo "[USER3_BOOKING]" >> config.ini
        echo "date = ${USER3_BOOKING_DATE}" >> config.ini
        echo "time = ${USER3_BOOKING_TIME}" >> config.ini
        echo "facility = ${USER3_BOOKING_FACILITY}" >> config.ini
        echo "cell_number = ${USER3_BOOKING_CELL_NUMBER}" >> config.ini
        echo "booking_reason = ${USER3_BOOKING_REASON}" >> config.ini
        echo "" >> config.ini
        
        echo "[USER4_LOGIN]" >> config.ini
        echo "url = ${USER4_LOGIN_URL}" >> config.ini
        echo "username = ${USER4_LOGIN_USERNAME}" >> config.ini
        echo "password = ${USER4_LOGIN_PASSWORD}" >> config.ini
        echo "" >> config.ini
        echo "[USER4_BOOKING]" >> config.ini
        echo "date = ${USER4_BOOKING_DATE}" >> config.ini
        echo "time = ${USER4_BOOKING_TIME}" >> config.ini
        echo "facility = ${USER4_BOOKING_FACILITY}" >> config.ini
        echo "cell_number = ${USER4_BOOKING_CELL_NUMBER}" >> config.ini
        echo "booking_reason = ${USER4_BOOKING_REASON}" >> config.ini

    - name: Run booking script
      run: |
        python main.py --headless --quiet --screenshots

    - name: Generate dashboard
      run: |
        python scripts/generate_dashboard.py

    - name: Deploy Dashboard
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dashboard