name: Court Booking Automation

on:
  schedule:
    - cron: '30 3 * * *'  # 3:30 UTC = 12:00 AM Newfoundland Time
  workflow_dispatch:  # Allows manual trigger from GitHub UI
  repository_dispatch:  # Allows API triggers
    types: [manual_trigger]

permissions:
  actions: write
  contents: write

jobs:
  book-courts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: '114.0.5735.90'

    - name: Install dependencies
      run: |
        sudo apt-get install -y libgbm-dev
        pip install --upgrade pip
        pip install -r requirements.txt selenium webdriver-manager pytz

    - name: Generate config file
      env:
        # User 1 Configuration
        USER1_LOGIN_URL: ${{ secrets.USER1_LOGIN_URL }}
        USER1_LOGIN_USERNAME: ${{ secrets.USER1_LOGIN_USERNAME }}
        USER1_LOGIN_PASSWORD: ${{ secrets.USER1_LOGIN_PASSWORD }}
        USER1_BOOKING_DATE: ${{ secrets.USER1_BOOKING_DATE }}
        USER1_BOOKING_TIME: ${{ secrets.USER1_BOOKING_TIME }}
        USER1_BOOKING_FACILITY: ${{ secrets.USER1_BOOKING_FACILITY }}
        USER1_BOOKING_CELL_NUMBER: ${{ secrets.USER1_BOOKING_CELL_NUMBER }}
        USER1_BOOKING_REASON: ${{ secrets.USER1_BOOKING_REASON }}

        # User 2 Configuration
        USER2_LOGIN_URL: ${{ secrets.USER2_LOGIN_URL }}
        USER2_LOGIN_USERNAME: ${{ secrets.USER2_LOGIN_USERNAME }}
        USER2_LOGIN_PASSWORD: ${{ secrets.USER2_LOGIN_PASSWORD }}
        USER2_BOOKING_DATE: ${{ secrets.USER2_BOOKING_DATE }}
        USER2_BOOKING_TIME: ${{ secrets.USER2_BOOKING_TIME }}
        USER2_BOOKING_FACILITY: ${{ secrets.USER2_BOOKING_FACILITY }}
        USER2_BOOKING_CELL_NUMBER: ${{ secrets.USER2_BOOKING_CELL_NUMBER }}
        USER2_BOOKING_REASON: ${{ secrets.USER2_BOOKING_REASON }}
      run: |
        # Config generation script remains the same
        echo "[USER1_LOGIN]" > config.ini
        echo "url = ${USER1_LOGIN_URL}" >> config.ini
        echo "username = ${USER1_LOGIN_USERNAME}" >> config.ini
        echo "password = ${USER1_LOGIN_PASSWORD}" >> config.ini
        echo "" >> config.ini
        echo "[USER1_BOOKING]" >> config.ini
        echo "date = ${USER1_BOOKING_DATE}" >> config.ini
        echo "time = ${USER1_BOOKING_TIME}" >> config.ini
        echo "facility = ${USER1_BOOKING_FACILITY}" >> config.ini
        echo "cell_number = ${USER1_BOOKING_CELL_NUMBER}" >> config.ini
        echo "booking_reason = ${USER1_BOOKING_REASON}" >> config.ini
        echo "" >> config.ini
        
        echo "[USER2_LOGIN]" >> config.ini
        echo "url = ${USER2_LOGIN_URL}" >> config.ini
        echo "username = ${USER2_LOGIN_USERNAME}" >> config.ini
        echo "password = ${USER2_LOGIN_PASSWORD}" >> config.ini
        echo "" >> config.ini
        echo "[USER2_BOOKING]" >> config.ini
        echo "date = ${USER2_BOOKING_DATE}" >> config.ini
        echo "time = ${USER2_BOOKING_TIME}" >> config.ini
        echo "facility = ${USER2_BOOKING_FACILITY}" >> config.ini
        echo "cell_number = ${USER2_BOOKING_CELL_NUMBER}" >> config.ini
        echo "booking_reason = ${USER2_BOOKING_REASON}" >> config.ini

    - name: Run booking script
      run: |
        python main.py --headless --screenshots

    - name: Generate dashboard
      run: |
        python scripts/generate_dashboard.py

    - name: Deploy Dashboard
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PAT_TOKEN }}  # Using PAT instead of default token
        publish_dir: ./dashboard
        keep_files: true  # Preserve previous deployment history

    - name: Debug Output
      run: |
        echo "Manual trigger received!"
        echo "Event type: ${{ github.event_name }}"
        echo "Triggered by: ${{ github.actor }}"
        echo "Payload: ${{ toJson(github.event.client_payload) }}"